
baseURL = "https://notohh.dev"
title = "notohh"
languageCode = "en-us"
theme = "hello-friend-ng"      # https://github.com/rhazdon/hugo-theme-hello-friend-ng

PygmentsCodeFences = false
PygmentsStyle = "monokai"

pagination.pagerSize = 10

archetypeDir = "archetypes"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"

buildDrafts = false
buildFuture = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
enableMissingTranslationPlaceholders = false
disableRSS = true
disableSitemap = true
disable404 = false
disableHugoGeneratorInject = false

description = "notohh.dev"


homeSubtitle = "notohh.dev"
disableReadOtherPosts = false
enableThemeToggle = false
enableSharingButtons = false


enableGlobalLanguageMenu = true

customCSS = []
customJS = []

justifyContent = false

[params.footer]
rss = false
copyright = false
author = false

bottomText = [
  "powered by <a href=\"http://gohugo.io\">hugo</a>",
  "site <a href=\"https://git.flake.sh/notohh/notohh.dev\">source</a>",
]

[params.favicon.color]
mask = "#1b1c1d"
msapplication = "#1b1c1d"
theme = "#1b1c1d"

[params.logo]
logoMark = ">"
logoText = "$ cd /home/"
logoHomeLink = "/"
# logoCursorDisabled = false
logoCursorColor = "#A9A9B3"
logoCursorAnimate = "1s"
logoCursorPathname = true

[[params.social]]
name = "mastodon"
url = "https://fosstodon.org/@notohh"

[[params.social]]
name = "bluesky"
url = "https://bsky.app/profile/flake.sh"

[[params.social]]
name = "gpg"
url = "https://keys.openpgp.org/search?q=+C3CB+3B31+AF3F+986C+39E0++BE5B+BD47+506D+475E+E86D"

[[params.social]]
name = "git"
url = "https://git.flake.sh/notohh"

[[params.social]]
name = "twitch"
url = "https://www.twitch.tv/notohh"

[[params.social]]
name = "lastfm"
url = "https://www.last.fm/user/notoh"


[languages]
[languages.en]
weight = 1

[menu]
[[menu.main]]
identifier = "about"
name = "about"
url = "about/"
[[menu.main]]
identifier = "projects"
name = "projects"
url = "projects/"
[[menu.main]]
identifier = "status"
name = "status"
url = "https://status.flake.sh/status/kumo"
